"""empty message

Revision ID: 0d70368e71d8
Revises: 5e0252d8042c
Create Date: 2024-07-10 17:25:41.438464

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")



# revision identifiers, used by Alembic.
revision = '0d70368e71d8'
down_revision = '5e0252d8042c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissionTickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissionTickets', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
