"""empty message

Revision ID: 61cb63de5cda
Revises: d6fff72c2000
Create Date: 2024-08-15 20:03:03.669946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cb63de5cda'
down_revision = 'd6fff72c2000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('admission_ticket_purchases', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('admission_tickets', schema=None) as batch_op:
        batch_op.drop_column('day')

    with op.batch_alter_table('ticket_types_purchased', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_types_purchased', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admission_ticket_purchases', ['purchase_id'], ['id'])
        batch_op.create_foreign_key(None, 'admission_ticket_types', ['type_id'], ['id'])

    with op.batch_alter_table('admission_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('admission_ticket_purchases', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'admission_tickets', ['admission_id'], ['id'])

    # ### end Alembic commands ###
