"""empty message

Revision ID: ef3ed56c59a8
Revises: 1df5e8620f06
Create Date: 2024-08-06 16:18:56.716088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3ed56c59a8'
down_revision = '1df5e8620f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_tickets', schema=None) as batch_op:
        batch_op.drop_column('month')

    # ### end Alembic commands ###
