"""empty message

Revision ID: 9492b89e5f50
Revises: 0d70368e71d8
Create Date: 2024-07-10 18:23:11.627193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9492b89e5f50'
down_revision = '0d70368e71d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('event_duration', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('members_only', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('members_only')
        batch_op.drop_column('event_duration')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
