"""empty message

Revision ID: d6fff72c2000
Revises: ef3ed56c59a8
Create Date: 2024-08-09 14:39:46.665834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fff72c2000'
down_revision = 'ef3ed56c59a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_ticket_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admission_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_ticket_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'admission_tickets', ['admission_id'], ['id'])

    # ### end Alembic commands ###
