"""empty message

Revision ID: 69af429007b8
Revises: 08c4899f8056
Create Date: 2024-07-15 14:36:49.445806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69af429007b8'
down_revision = '08c4899f8056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_ticket_types', schema=None) as batch_op:
        batch_op.alter_column('admission_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('exposition_images', schema=None) as batch_op:
        batch_op.alter_column('piece_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exposition_images', schema=None) as batch_op:
        batch_op.alter_column('piece_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('admission_ticket_types', schema=None) as batch_op:
        batch_op.alter_column('admission_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
