"""empty message

Revision ID: 1df5e8620f06
Revises: afd5ca5250f2
Create Date: 2024-08-06 16:16:39.268376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df5e8620f06'
down_revision = 'afd5ca5250f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=100000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('admission_tickets', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
